# Generated by Django 3.2.5 on 2021-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
