# Generated by Django 3.2.3 on 2021-07-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(max_length=20)),
                ('eth', models.CharField(max_length=20)),
                ('bch', models.CharField(max_length=20)),
                ('lth', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBnb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionUtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionBch',
        ),
    ]
