# Generated by Django 3.2.3 on 2021-07-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210709_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='lth',
            new_name='bnb',
        ),
        migrations.AddField(
            model_name='balance',
            name='utc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
